version: "3.8"

services:
  wallet1:
    build: .
    container_name: wallet1
    volumes:
      - ./wallet1_data:/wallet_data
    entrypoint: ["minotari_console_wallet", "--base-path", "/wallet_data"]
    command: [
        "--network",
        "esmeralda",
        # "--custom_base_node",
        # "https://rpc.esmeralda.tari.com",
      ]

  wallet2:
    build: .
    container_name: wallet2
    volumes:
      - ./wallet2_data:/wallet_data
    entrypoint: ["minotari_console_wallet", "--base-path", "/wallet_data"]
    command: ["--network", "esmeralda"]
    ports:
      - "44871:44871"
  wallet3:
    build: .
    container_name: wallet3
    volumes:
      - ./wallet3_data:/wallet_data
    entrypoint: ["minotari_console_wallet", "--base-path", "/wallet_data"]
    command: ["--network", "esmeralda"]

  wallet4:
    build: .
    container_name: wallet4
    volumes:
      - ./wallet4_data:/wallet_data
    entrypoint: ["minotari_console_wallet", "--base-path", "/wallet_data"]
    command: ["--network", "esmeralda"]
